config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  before_save :downcase_email

  validates :name, presence: true
  validates :email, presence: true, 
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  self.per_page = 25

  private
    def downcase_email
      email.downcase!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :set_users, only: [:create, :update]
  helper_method :sort_column, :sort_direction

  def index
    @user = User.new 
    if params[:query].present?
      if Rails.env.development?
        @users = User.where("name LIKE ? or email LIKE ?", "%#{params[:query]}%", "%#{params[:query]}%").order("#{sort_column} #{sort_direction}").paginate(page: params[:page])
      else
        @users = User.where("name ILIKE ? or email ILIKE ?", "%#{params[:query]}%", "%#{params[:query]}%").order("#{sort_column} #{sort_direction}").paginate(page: params[:page])
      end
    else
      set_users
    end
  end

  def new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      flash[:success] = "New User: #{@user.name} was successfully added."
      redirect_back fallback_location: root_url
    else
      flash[:danger] = "Name/Email missing or Email already used. New User was not added."
      redirect_back fallback_location: root_url
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "User #{@user.name} was successfully updated."
      redirect_back fallback_location: root_url
    else
      render :edit
    end
  end

  def destroy
    gone_user = @user
    @user.destroy
    flash[:danger] = "User #{gone_user.name} was deleted."
    redirect_back fallback_location: root_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :title, :phone, :status)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def set_users
      @users = User.order("#{sort_column} #{sort_direction}").paginate(page: params[:page])
    end

    def sort_column
      User.column_names.include?(params[:sort]) ? params[:sort] : "updated_at"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title=nil, query=nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, { sort: column, direction: direction, query: query }
  end  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>User List</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <% flash.each do |type, message| %>
        <%= content_tag :div, message, class: "alert alert-#{type}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_editUser.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id='editUserModal_<%= @user.id %>_Label'>Edit User</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <%= form_with(model: @user, remote: true, method: "put") do |form| %>
        <%= render 'form_fields', form: form %>
      <% end %>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    </div>
  </div>
</div>

app/views/users/_form_fields.html.erb
<div class="form-group">
  <%= form.label :title %>
  <%= form.text_field :title, placeholder: "Mr., Mrs., Miss, Dr., etc.", class: "form-control" %>
  <%= form.label :name %>
  <%= form.text_field :name, autofocus: true, placeholder: "Last, First", class: "form-control" %>
  <%= form.label :email %>
  <%= form.email_field :email, class: "form-control" %>
  <%= form.label :phone %>
  <%= form.text_field :phone, class: "form-control" %>
  <%= form.label :status %>
  <%= form.select :status, [['inactive', false], ['active', true]], class: "form-control" %>
  <%= form.submit "Enter", class: "form-control btn btn-primary" %>
</div>

app/views/users/_user.html.erb
<tr id="user_<%= user.id %>">
  <td><%= user.updated_at.strftime("%d %b %Y - %H:%M") %></td>
  <td><%= user.title %></td>  
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%= user.phone %></td>
  <td class="status_<%= user.status %>"><%= user.status ? 'active' : 'inactive' %></td>
  <td><%= link_to "Edit", edit_user_path(user), remote: true, class: "btn btn-success btn-sm" %>
  </td>
  <td>
    <%= link_to "Delete", user_path(user), { method: :delete, data: { confirm: 'Confirm delete' }, class: "btn btn-danger btn-sm" } %>
  </td>
</tr>

app/views/users/_userList.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sortable "updated_at", "Last Updated", params[:query] %></th>
      <th><%= sortable "title", "Title", params[:query] %></th>
      <th><%= sortable "name", "Name", params[:query] %></th>
      <th><%= sortable "email", "Email", params[:query] %></th>
      <th><%= sortable "phone", "Phone", params[:query] %></th>
      <th><%= sortable "status", "Status", params[:query] %></th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody id="users">
    <%= render @users %>
  </tbody>
</table>
<div id="paginationing">
  <%= will_paginate @users %>
</div>

app/views/users/edit.js.erb
$('#editModal').html("<%= j (render partial: 'editUser') %>");
$('#editModal').modal('show');

app/views/users/index.html.erb
<h1><%= link_to "Users", users_path %></h1>
<a href='/users/new' data-toggle="modal" data-target="#newUserModal" class="btn btn-primary btn-sm">Add New User</a>

<div class="form-group">
  <%= form_with(url: users_path, method: "get") do %>
    <%= label_tag :query, "Filter by Name / Email:" %>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "Search", class: "btn btn-success btn-sm" %>
  <% end %>
</div>

<div id="usersList">
  <%= render 'userList' %>
</div>

<div class="modal fade" id="newUserModal" tabindex="-1" role="dialog" aria-labelledby="newUserModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newUserModalLabel">Add New User</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with(model: @user, remote: true) do |form| %>
          <%= render 'form_fields', form: form %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editUserModalLabel">
</div>

app/views/users/index.js.erb
$("#usersList").html("<%= j (render 'userList') %>");